# -------------------------------
# Ultra light base: Alpine Linux
# -------------------------------
FROM python:3.12.2-alpine3.21

# -------------------------------
# Environment Variables
# -------------------------------
ENV LANG=C.UTF-8 \
    PYTHONUNBUFFERED=1

# -------------------------------
# Install dependencies
# -------------------------------
RUN apk add --no-cache \
    bash \
    coreutils \
    imagemagick \
    tesseract-ocr \
    tesseract-ocr-langdata \
    jq \
    gawk \
    sed \
    nano \
    nginx \
    curl \
    git \
    tini \
    build-base \
    libstdc++ \
    shadow \
    procps \
    file \
    nodejs \
    npm \
    \
    # Upgrade pip
    && pip install --no-cache-dir --upgrade pip setuptools wheel \
    \
    # Verify installation
    && node -v \
    && npm -v \
    \
    # Cleanup temporary files
    && rm -rf /var/cache/apk/* /tmp/* /root/.cache

# -------------------------------
# Create non-root user: appuser
# -------------------------------
RUN adduser -D -h /app appuser
WORKDIR /app
USER appuser
RUN mkdir -p /app/scripts
RUN mkdir -p /app/frontend
RUN mkdir -p /app/backend
RUN mkdir -p /app/logs

# -------------------------------
# Copy nginx and SSH Configuration
# -------------------------------
RUN mkdir -p /run/nginx
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# -------------------------------
# Copy start script
# -------------------------------
COPY ./scripts/ocr-container-start.sh /usr/local/bin/ocr-container-start.sh
RUN chmod +x /usr/local/bin/ocr-container-start.sh

# -------------------------------
# Exposed Ports: 443 (Nginx), 3443 (Node.js / Express)
# -------------------------------
EXPOSE 443
EXPOSE 3443

# -------------------------------
# Entrypoint
# -------------------------------
ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/ocr-container-start.sh"]
CMD ["bash"]
