server {
  listen 443 ssl;
  server_name codexai.eniac-corp.com;
  ssl_certificate /app/ssl/ssl.crt;
  ssl_certificate_key /app/ssl/ssl.key;
  root /app/frontend/browser;
  index index.html;
  error_page 500 502 503 504 /50x.html;
  location /api/ {
    proxy_pass https://codexai.eniac-corp.com:8443/api/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
